//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleActBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAKpalkinto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAKpalkinto()
        {
            this.SAKtehdytteots = new HashSet<SAKtehdytteot>();
        }
    
        public int PalkintoID { get; set; }
        public string PalkintoNimi { get; set; }
        public Nullable<int> PalkinnonTarjoajaID { get; set; }
        public byte[] Palkintokuva { get; set; }
        public Nullable<bool> KuvanKoko { get; set; }
    
        public virtual SAKpalkinnontarjoaja SAKpalkinnontarjoaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAKtehdytteot> SAKtehdytteots { get; set; }
    }
}
