//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleActBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAKpalkinnontarjoaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAKpalkinnontarjoaja()
        {
            this.SAKpalkintoes = new HashSet<SAKpalkinto>();
        }
    
        public int PalkinnontarjoajaID { get; set; }
        public string YrityksenNimi { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Sahkoposti { get; set; }
        public string Puhelinnumero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAKpalkinto> SAKpalkintoes { get; set; }
    }
}
