//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleActBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAKtehdytteot
    {
        public int TehdytTeotID { get; set; }
        public Nullable<int> KayttajaID { get; set; }
        public Nullable<System.DateTime> Tekopvm { get; set; }
        public Nullable<int> PalkintoID { get; set; }
        public Nullable<System.DateTime> VoimassaOloPvm { get; set; }
        public Nullable<int> TekoID { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual SAKkayttaja SAKkayttaja { get; set; }
        public virtual SAKpalkinto SAKpalkinto { get; set; }
        public virtual SAKteot SAKteot { get; set; }
    }
}
